### ISSUE TITLE
After upgrading to Slick universal to 3.0.0-beta0 getting error

### ISSUE THREAD

**Issue by lajith111** [ghiscoding/slickgrid-universal#979]
### Describe the bug

For testing purpose i have upgraded Slick universal to 3.0.0-beta0 . In my project excel export, graphql .

I am getting below error

```
Error: src/app/shared/shared.module.ts:29:35 - error TS2322: Type 'ExcelExportService' is not assignable to type 'ExternalResource'.
  Types of property 'init' are incompatible.
    Type '(grid: SlickGrid, containerService: ContainerService) => void' is not assignable to type '(grid: SlickGrid, container: ContainerService) => void'.
      Types of parameters 'grid' and 'grid' are incompatible.
        Type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickGrid.interface").SlickGrid' is not assignable to type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickGrid.interface").SlickGrid'.
          Types of property 'editActiveCell' are incompatible.
            Type '(editor: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/editor.interface").Editor | import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickC...' is not assignable to type '(editor: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/editor.interface").Editor | import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickCompositeEditor.interface").SlickCompositeEditor, preClickModeO...'.
              Types of parameters 'editor' and 'editor' are incompatible.
                Type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/editor.interface").Editor | import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickCompositeEditor.interface").SlickCompositeEditor' is not assignable to type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/editor.interface").Editor | import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickCompositeE...'.
                  Type 'Editor' is not assignable to type 'Editor | SlickCompositeEditor'.
                    Type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/editor.interface").Editor' is not assignable to type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/editor.interface").Editor'.
                      Types of property 'init' are incompatible.
                        Type '(args?: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/editorArguments.interface").EditorArguments) => void' is not assignable to type '(args?: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/editorArguments.interface").EditorArguments) => void'.
                          Types of parameters 'args' and 'args' are incompatible.
                            Type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/editorArguments.interface").EditorArguments' is not assignable to type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/editorArguments.interface").EditorArguments'.
                              The types of 'column.asyncPostRender' are incompatible between these types.
                                Type '(domCellNode: any, row: number, dataContext: any, columnDef: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/column.interface").Column<any>) => void' is not assignable to type '(domCellNode: any, row: number, dataContext: any, columnDef: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/column.interface").Column<any>) => void'.
                                  Types of parameters 'columnDef' and 'columnDef' are incompatible.
                                    Type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/column.interface").Column<any>' is not assignable to type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/column.interface").Column<any>'.
                                      The types of 'cellMenu.onExtensionRegistered' are incompatible between these types.
                                        Type '(plugin: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/extensions/slickCellMenu").SlickCellMenu) => void' is not assignable to type '(plugin: import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/extensions/slickCellMenu").SlickCellMenu) => void'.
                                          Types of parameters 'plugin' and 'plugin' are incompatible.
                                            Type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/extensions/slickCellMenu").SlickCellMenu' is not assignable to type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/extensions/slickCellMenu").SlickCellMenu'.
                                              Property 'extensionUtility' is protected but type 'SlickCellMenu' is not a class derived from 'SlickCellMenu'.

29       registerExternalResources: [new ExcelExportService()],
                                     ~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/views/account/account-list/account-list.component.ts:89:13 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

89             service: this.graphqlService,
               ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/bank/bank-list/bank-list.component.ts:63:9 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.  
  Types of property 'init' are incompatible.
    Type '(serviceOptions?: GraphqlServiceOption, pagination?: Pagination, grid?: SlickGrid, sharedService?: SharedService) => void' is not assignable to type '(serviceOptions?: any, pagination?: Pagination, grid?: SlickGrid, sharedService?: SharedService) => void'.
      Types of parameters 'grid' and 'grid' are incompatible.
        Type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickGrid.interface").SlickGrid' is not assignable to type 'import("D:/Personal/Workspace/CorePigmyWeb/node_modules/@slickgrid-universal/common/dist/types/interfaces/slickGrid.interface").SlickGrid'.

63         service: new GraphqlService(),
           ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/branch/branch-list/branch-list.component.ts:81:9 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

81         service: this.graphqlService,
           ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/collection/collection-approve-list/collection-approve-list.component.ts:84:11 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

84           service: new GraphqlService(),
             ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/collection/collection-list/collection-list.component.ts:86:9 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

86         service: this.graphqlService,
           ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/reports/collection-summary-list/collection-summary-list.component.ts:96:9 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

96         service: this.graphqlService,
           ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/reports/sms-usage-list/sms-usage-list.component.ts:81:9 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

81         service: this.graphqlService,
           ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/reports/transaction-history-list/transaction-history-list.component.ts:69:9 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

69         service: this.graphqlService,
           ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/reports/transaction-log-list/transaction-log-list.component.ts:86:9 - error TS2322: Type 'GraphqlService' is not assignable to type 'BackendService'.

86         service: this.graphqlService,
           ~~~~~~~

  node_modules/angular-slickgrid/node_modules/@slickgrid-universal/common/dist/types/interfaces/backendServiceApi.interface.d.ts:9:5
    9     service: BackendService;
          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'


Error: src/app/views/transaction/transaction-list/transaction-list.component.ts:84:9 - error TS2322: Type 'GraphqlService' is not assignable to typ          ~~~~~~~
    The expected type comes from property 'service' which is declared here on type 'BackendServiceApi'
```

### Reproduction

Removed jquery package and also remove reference in angular.json. I don't no other need to change 

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| angular             | 15.2.0"|
| angular-slickgrid   | 5.6.4"|
| Slickgrid-Universal | 3.0.0.beata0|
| TypeScript          | 4.8.4|
| Browser(s)          | Version 113.0.5672.127|
| System OS           | Windows 11 |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
@lajith111 
Alright today is the day... see Angular-Slickgrid [v6.0.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v6.0.0) release and follow the migration shown in the release. 

Cheers ⭐

**Comment by lajith111** [comment]
@ghiscoding i have tested sllckgrid with graphsql & excel export service in my project..it is working fine.
